Set different way of using env variables

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -164,6 +164,7 @@ jobs:
         plugin-test-dir: ${{ fromJson(needs.discover-plugin-tests.outputs.plugin-matrix) }}
     secrets:
       token: ${{ secrets.GITHUB_TOKEN }}
+    
     with:
       image-build-artifact-name: 'build-docker-image'
       image-tarball-file: 'image.tar'
@@ -172,33 +173,6 @@ jobs:
       image-id: ${{ needs.build-image.outputs.image-id }}
       image-name: ${{ github.repository }}
       setup-script: |
-
-        # List of plugins that need .env
-        PLUGINS_WITH_ENV=("cert-auth" "limit-size")
-
-        for plugin in "${PLUGINS_WITH_ENV[@]}"; do
-          env_file="tests/$plugin/.env"
-          echo "Creating .env file for plugin: $plugin"
-
-          cat <<EOF > "$env_file"
-        BULT_CLIENT_CHAIN=$(echo "${BULT_CLIENT_CHAIN}" | base64 -d)
-        SERVER_KEY=$(echo "${SERVER_KEY}" | base64 -d)
-        SERVER_CERT=$(echo "${SERVER_CERT}" | base64 -d)
-        SELF_SIGNED_CA=$(echo "${SELF_SIGNED_CA}" | base64 -d)
-        EOF
-
-          echo ".env file created at $env_file"
-        done
-
-        for dir in $(find tests -mindepth 1 -maxdepth 1 -type d); do
-          env_file="$dir/.env"
-          if [ -f "$env_file" ]; then
-            echo "--- $env_file ---"
-            cat "$env_file"
-          else
-            echo "--- $env_file does not exist ---"
-          fi
-        done
 
         # Start the services
         docker compose -f tests/${{ matrix.plugin-test-dir }}/docker-compose.yaml up -d
@@ -215,6 +189,13 @@ jobs:
         echo "APISIX health check:"
         docker ps
         docker compose -f tests/${{ matrix.plugin-test-dir }}/docker-compose.yaml ps
+
+          # Automatically print all environment variables for each service
+        echo "🔹 Environment variables in each container:"
+        for service in $(docker compose -f tests/${{ matrix.plugin-test-dir }}/docker-compose.yaml config --services); do
+          echo "--- $service ---"
+          docker compose -f tests/${{ matrix.plugin-test-dir }}/docker-compose.yaml exec $service env || echo "Failed to exec $service"
+        done
 
 
       teardown-script: |
